version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    networks:
      - laravel-net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: projects
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: samir
      POSTGRES_PASSWORD: samir
    volumes:
      - db_data:/var/lib/postgres
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge
